name: Security Pipeline (SCA + DAST)

on: [push]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- СТАДИЯ SCA (ЛР 12) ---
      # Она должна быть зеленой, поэтому в requirements.txt должны быть новые версии
      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'json'
          output: 'trivy_report.json'

      # --- СТАДИЯ DAST (ЛР 13) ---
      
      # 1. Собираем и запускаем твой Fitness Tracker
      - name: Build and Run App
        run: |
          docker build -t fitness-app .
          docker run -d -p 5000:5000 --name tracker fitness-app
          sleep 15 # Даем Flask время полностью подняться

      # 2. ПОДГОТОВКА: Создаем файл отчета заранее и даем права Docker-у на запись в него
      - name: Prepare report file
        run: |
          touch report_json.json
          chmod 777 report_json.json

      # 3. Запуск сканера OWASP ZAP
      - name: Run OWASP ZAP
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          # Явно просим ZAP записать результат в наш подготовленный файл
          cmd_options: '-J report_json.json'
          fail_action: false

      # 4. Проверка Security Gate через Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Check Security Gate
        run: python security_gate.py

      # 5. Сохранение всех отчетов (чтобы прикрепить к лабе)
      - name: Upload All Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            trivy_report.json
            report_json.json
